# Generated by Django 4.2.6 on 2023-10-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido')),
                ('tipo_documento', models.CharField(max_length=30, verbose_name='Tipo Documento')),
                ('numero_documento', models.CharField(max_length=30, verbose_name='Nro. Documento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('B', 'Baja')], default='Activo', max_length=1, verbose_name='Estado')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudades.ciudad')),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
