# Generated by Django 4.2.6 on 2023-10-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='ciudad',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
    ]
