# Generated by Django 4.2.6 on 2023-10-29 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0001_initial'),
        ('personas', '0002_remove_persona_ciudad_delete_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ciudades.ciudad'),
            preserve_default=False,
        ),
    ]
