# Generated by Django 4.2.6 on 2023-10-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_persona_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('B', 'Baja')], default='Activo', max_length=1, verbose_name='Estado'),
        ),
    ]
