# Generated by Django 4.2.6 on 2023-10-19 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre Ciudad')),
                ('departamento', models.CharField(max_length=60, verbose_name='Departamento')),
                ('codigo_postal', models.IntegerField(verbose_name='Código Postal')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.CharField(choices=[('M', 'Mala'), ('B', 'Buena'), ('E', 'Excelente')], max_length=1, verbose_name='Calificación')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('B', 'Baja')], max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=30, unique=True, verbose_name='Nro. Cuenta')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Alta')),
                ('tipo_cuenta', models.CharField(choices=[('C', 'Cuenta Corriente'), ('A', 'Caja de Ahorro')], max_length=1, verbose_name='Tipo de Cuenta')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('B', 'Baja')], max_length=1, verbose_name='Estado')),
                ('saldo', models.FloatField(verbose_name='Saldo')),
                ('numero_contrato', models.CharField(max_length=40, verbose_name='Nro. Contrato')),
                ('costo_mantenimiento', models.FloatField(verbose_name='Costo Mantenimiento')),
                ('promedio_acreditacion', models.FloatField(verbose_name='Promedio Acreditación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
                ('simbolo', models.CharField(max_length=10, verbose_name='Símbolo')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido')),
                ('tipo_documento', models.CharField(max_length=30, verbose_name='Tipo Documento')),
                ('numero_documento', models.CharField(max_length=30, verbose_name='Nro. Documento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('B', 'Baja')], max_length=1, verbose_name='Estado')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Movimiento')),
                ('tipo_movimiento', models.CharField(choices=[('DEP', 'Depósito'), ('RET', 'Retiro'), ('DEB', 'Débito'), ('CRE', 'Crédito')], max_length=3, verbose_name='Tipo de Movimiento')),
                ('saldo_anterior', models.FloatField(verbose_name='Saldo Anterior')),
                ('saldo_actual', models.FloatField(verbose_name='Saldo Actual')),
                ('monto_movimiento', models.FloatField(verbose_name='Monto Movimiento')),
                ('numero_cuenta_origen', models.CharField(max_length=30, verbose_name='Nro. Cuenta Origen')),
                ('numero_cuenta_destino', models.CharField(max_length=30, verbose_name='Nro. Cuenta Destino')),
                ('canal', models.CharField(choices=[('W', 'Web'), ('C', 'Caja'), ('A', 'App')], max_length=1, verbose_name='Canal')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.moneda'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.persona'),
        ),
    ]
