# Generated by Django 4.2.6 on 2023-10-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='moneda',
            options={'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name_plural': 'Personas'},
        ),
    ]
