# Generated by Django 4.2.6 on 2023-10-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='moneda',
            options={'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='cuenta',
            name='bloqueada',
            field=models.BooleanField(default=False, verbose_name='Bloqueada'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactiva')], max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactiva')], max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactiva')], max_length=1, verbose_name='Estado'),
        ),
    ]
