# Generated by Django 4.2.6 on 2023-10-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_ciudad_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloqueada',
            field=models.BooleanField(default=False, verbose_name='Bloqueada'),
        ),
    ]
