# Generated by Django 4.2.6 on 2023-10-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_cliente_bloqueada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='bloqueada',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='bloqueada',
            field=models.BooleanField(default=False, verbose_name='Bloqueada'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, verbose_name='Estado'),
        ),
    ]
