# Generated by Django 4.2.6 on 2023-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre Ciudad')),
                ('departamento', models.CharField(max_length=60, verbose_name='Departamento')),
                ('codigo_postal', models.IntegerField(verbose_name='Código Postal')),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
    ]
